<?php
$conn = new mysqli("localhost", "root", "", "checklist");

if ($conn->connect_error) {
    die("Erro de conexão: " . $conn->connect_error);
}

$POSTO = $_POST['POSTO'];
$RE = $_POST['RE'];
$EMAIL_GEO = $_POST['EMAIL_GEO'];
$GEO_ENVIADAS = $_POST['GEO_ENVIADAS'];
$FAMILY_LINK = $_POST['FAMILY_LINK'];
$TESTE_FAMILY_LINK = $_POST['TESTE_FAMILY_LINK'];
$BASTAO = $_POST['BASTAO'];
$RETIRADO_CHIP = $_POST['RETIRADO_CHIP'];
$EMAIL_CASSIA = $_POST['EMAIL_CASSIA'];
$EMAIL_EBS = $_POST['EMAIL_EBS'];
$DESATIVACAO_EBS = $_POST['DESATIVACAO_EBS'];
$ALTERACAO_SEGWARE = $_POST['ALTERACAO_SEGWARE'];
$CLIENTE_FINDME = $_POST['CLIENTE_FINDME'];
$LOCAL_FINDME = $_POST['LOCAL_FINDME'];
$USUARIO_FINDME = $_POST['USUARIO_FINDME'];
$LOCALIZADOR_FINDME = $_POST['LOCALIZADOR_FINDME'];
$TESTE_LOGIN = $_POST['TESTE_LOGIN'];
$VERIFICAR_PONTOS_SIGMA = $_POST['VERIFICAR_PONTOS_SIGMA'];
$PONTOS_CARREGARA = $_POST['PONTOS_CARREGARA'];
$INT_POSTO_SIGMA = $_POST['INT_POSTO_SIGMA'];
$INT_PONTO_SIGMA = $_POST['INT_PONTO_SIGMA'];
$TESTE_PANICO = $_POST['TESTE_PANICO'];
$SISTEMA = $_POST['SISTEMA'];

$sql = "INSERT INTO checklist_data (POSTO, RE, EMAIL_GEO, GEO_ENVIADAS, FAMILY_LINK, TESTE_FAMILY_LINK, BASTAO, RETIRADO_CHIP, 
    EMAIL_CASSIA, EMAIL_EBS, DESATIVACAO_EBS, ALTERACAO_SEGWARE, CLIENTE_FINDME, LOCAL_FINDME, USUARIO_FINDME, LOCALIZADOR_FINDME, 
    TESTE_LOGIN, VERIFICAR_PONTOS_SIGMA, PONTOS_CARREGARA, INT_POSTO_SIGMA, INT_PONTO_SIGMA, TESTE_PANICO, SISTEMA) 
    VALUES ('$POSTO', '$RE', '$EMAIL_GEO', '$GEO_ENVIADAS', '$FAMILY_LINK', '$TESTE_FAMILY_LINK', '$BASTAO', '$RETIRADO_CHIP', 
    '$EMAIL_CASSIA', '$EMAIL_EBS', '$DESATIVACAO_EBS', '$ALTERACAO_SEGWARE', '$CLIENTE_FINDME', '$LOCAL_FINDME', '$USUARIO_FINDME', 
    '$LOCALIZADOR_FINDME', '$TESTE_LOGIN', '$VERIFICAR_PONTOS_SIGMA', '$PONTOS_CARREGARA', '$INT_POSTO_SIGMA', '$INT_PONTO_SIGMA', 
    '$TESTE_PANICO', '$SISTEMA')";

if ($conn->query($sql) === TRUE) {
    echo "Checklist salvo com sucesso!";
} else {
    echo "Erro ao salvar o checklist: " . $conn->error;
}

$conn->close();
?>
